apiVersion: v1
kind: Service
metadata:
    name: "gantik8s-2862"
    labels:
        app: "gantik8s-2862"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "gantik8s-2862"