on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ws1212053crr5ugfbutecq4q.azurecr.io
        username: ${{ secrets.acr_ws1212053crr5ugfbutecq4q_username }}
        password: ${{ secrets.acr_ws1212053crr5ugfbutecq4q_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t ws1212053crr5ugfbutecq4q.azurecr.io/gantik8s:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push ws1212053crr5ugfbutecq4q.azurecr.io/gantik8s:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_gantik8s_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep gantik8sbdef | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace gantik8sbdef`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: gantik8sbdef
        container-registry-url: ws1212053crr5ugfbutecq4q.azurecr.io
        container-registry-username: ${{ secrets.acr_ws1212053crr5ugfbutecq4q_username }}
        container-registry-password: ${{ secrets.acr_ws1212053crr5ugfbutecq4q_password }}
        secret-name: gantik8sdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: gantik8sbdef
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          ws1212053crr5ugfbutecq4q.azurecr.io/gantik8s:${{ github.sha }}
        imagepullsecrets: |
          gantik8sdockerauth
